### PR TITLE
Fix for normalize filename in ParserController

### PR DESCRIPTION
**Pull request by rmartinc**
Fix for: https://issues.jboss.org/browse/JBEAP-10134

### CODE REVIEW

**Comment by kabir** [comment]
@rmartinc When including this fix into WildFly, it seems to cause problems on windows: https://github.com/wildfly/wildfly/pull/11533

**Comment by rmartinc** [comment]
@kabir I don't have access to that CI page. I cannot see the problem.

**Comment by ctomc** [comment]
@rmartinc just use "login as guest" at bottom right corner of login form.

**Comment by rmartinc** [comment]
Ok, I think that using Paths was a bad idea. In windows it sets the path to "\WEB-INF\header.jsp" and generates this error.

**Comment by rmartinc** [comment]
IMHO this change should be reverted, the cure is worse than the disease. Then we can check how the file name is normalized. Sorry for that, but I never foresee those nasty windows results.

**Comment by kabir** [comment]
@rmartinc Stuart is away until Monday. Are you able to revert locally and start from scratch if you are planning on investigating?

**Comment by kabir** [comment]
@rmartinc thanks! Can you open a PR and Stuart can check it on Monday?

**Comment by rmartinc** [comment]
Done! But give this issue more thought, the reason is clear, how to fix it is not for me... Do you need a jira for this?

https://github.com/undertow-io/jastow/pull/40

**Comment by kabir** [comment]
@rmartinc I guess you can just reuse UNDERTOW-1398?

**Pull request merged**
